/*
 * Copyright 2018 vasgat.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package certh.iti.mklab.music.charts.extraction.framework.chartUtils;

import java.util.HashMap;

/**
 *
 * @author vasgat
 */
public class CountryCodes {

    HashMap<String, String> country_codes;

    public CountryCodes() {
        this.country_codes = new HashMap();
        this.country_codes.put("ca_ab", "alberta");
        this.country_codes.put("pr", "puerto rico");
        this.country_codes.put("ps", "palestinian territory");
        this.country_codes.put("pt", "portugal");
        this.country_codes.put("pw", "palau");
        this.country_codes.put("py", "paraguay");
        this.country_codes.put("us_ky", "kentucky");
        this.country_codes.put("us_ks", "kansas");
        this.country_codes.put("qa", "qatar");
        this.country_codes.put("us_la", "louisiana");
        this.country_codes.put("ad", "andorra");
        this.country_codes.put("af", "afghanistan");
        this.country_codes.put("ag", "antigua and barbuda");
        this.country_codes.put("ai", "anguilla");
        this.country_codes.put("al", "albania");
        this.country_codes.put("am", "armenia");
        this.country_codes.put("ao", "angola");
        this.country_codes.put("aq", "antarctica");
        this.country_codes.put("ar", "argentina");
        this.country_codes.put("as", "american samoa");
        this.country_codes.put("at", "austria");
        this.country_codes.put("ca_qc", "quebec");
        this.country_codes.put("re", "reunion");
        this.country_codes.put("au", "australia");
        this.country_codes.put("aw", "aruba");
        this.country_codes.put("ax", "Aland islands");
        this.country_codes.put("az", "azerbaijan");
        this.country_codes.put("ro", "romania");
        this.country_codes.put("ba", "bosnia and herzegovina");
        this.country_codes.put("bb", "barbados");
        this.country_codes.put("rs", "serbia");
        this.country_codes.put("us_ms", "mississippi");
        this.country_codes.put("bd", "bangladesh");
        this.country_codes.put("be", "belgium");
        this.country_codes.put("ru", "russia");
        this.country_codes.put("bf", "burkina faso");
        this.country_codes.put("us_mn", "minnesota");
        this.country_codes.put("bg", "bulgaria");
        this.country_codes.put("rw", "rwanda");
        this.country_codes.put("us_mo", "missouri");
        this.country_codes.put("bh", "bahrain");
        this.country_codes.put("bi", "burundi");
        this.country_codes.put("bj", "benin");
        this.country_codes.put("bl", "saint bartholemy");
        this.country_codes.put("bm", "bermuda");
        this.country_codes.put("bn", "brunei darussalam");
        this.country_codes.put("bo", "bolivia");
        this.country_codes.put("sa", "saudi arabia");
        this.country_codes.put("us_mt", "montana");
        this.country_codes.put("bq", "bonaire");
        this.country_codes.put("sb", "solomon islands");
        this.country_codes.put("br", "brazil");
        this.country_codes.put("sc", "seychelles");
        this.country_codes.put("us_nc", "north carolina");
        this.country_codes.put("bs", "bahamas");
        this.country_codes.put("sd", "sudan");
        this.country_codes.put("us_nd", "north dakota");
        this.country_codes.put("bt", "bhutan");
        this.country_codes.put("se", "sweden");
        this.country_codes.put("bv", "bouvet island");
        this.country_codes.put("sg", "singapore");
        this.country_codes.put("bw", "botswana");
        this.country_codes.put("sh", "saint helena");
        this.country_codes.put("si", "slovenia");
        this.country_codes.put("by", "belarus");
        this.country_codes.put("sj", "svalbard and jan mayen");
        this.country_codes.put("bz", "belize");
        this.country_codes.put("sk", "slovakia");
        this.country_codes.put("sl", "sierra leone");
        this.country_codes.put("sm", "san marino");
        this.country_codes.put("sn", "senegal");
        this.country_codes.put("us_nj", "new jersey");
        this.country_codes.put("so", "somalia");
        this.country_codes.put("us_nh", "new hampshire");
        this.country_codes.put("ca", "canada");
        this.country_codes.put("us_ne", "nebraska");
        this.country_codes.put("sr", "suriname");
        this.country_codes.put("cc", "cocos (keeling) islands");
        this.country_codes.put("ss", "south sudan");
        this.country_codes.put("cd", "democratic republic of the congo");
        this.country_codes.put("st", "sao tome and principe");
        this.country_codes.put("ca_bc", "british columbia");
        this.country_codes.put("cf", "central african republic");
        this.country_codes.put("sv", "el salvador");
        this.country_codes.put("cg", "congo");
        this.country_codes.put("ch", "switzerland");
        this.country_codes.put("sx", "sint maarten (dutch part)");
        this.country_codes.put("ci", "cote d'ivoire");
        this.country_codes.put("sy", "syrian arab republic");
        this.country_codes.put("sz", "swaziland");
        this.country_codes.put("ck", "cook islands");
        this.country_codes.put("cl", "chile");
        this.country_codes.put("cm", "cameroon");
        this.country_codes.put("cn", "china");
        this.country_codes.put("co", "colombia");
        this.country_codes.put("cr", "costa rica");
        this.country_codes.put("tc", "turks and caicos islands");
        this.country_codes.put("td", "chad");
        this.country_codes.put("cu", "cuba");
        this.country_codes.put("tf", "french southern territories");
        this.country_codes.put("cv", "cape verde");
        this.country_codes.put("tg", "togo");
        this.country_codes.put("us_ma", "massachusetts");
        this.country_codes.put("cw", "curacao");
        this.country_codes.put("th", "thailand");
        this.country_codes.put("cx", "christmas island");
        this.country_codes.put("cy", "cyprus");
        this.country_codes.put("tj", "tajikistan");
        this.country_codes.put("cz", "czech republic");
        this.country_codes.put("tk", "tokelau");
        this.country_codes.put("tl", "timor-leste");
        this.country_codes.put("ca_sk", "saskatchewan");
        this.country_codes.put("tm", "turkmenistan");
        this.country_codes.put("tn", "tunisia");
        this.country_codes.put("to", "tonga");
        this.country_codes.put("us_mi", "michigan");
        this.country_codes.put("tr", "turkey");
        this.country_codes.put("us_md", "maryland");
        this.country_codes.put("us_me", "maine");
        this.country_codes.put("tt", "trinidad and tobago");
        this.country_codes.put("de", "germany");
        this.country_codes.put("tv", "tuvalu");
        this.country_codes.put("tw", "taiwan");
        this.country_codes.put("us_wy", "wyoming");
        this.country_codes.put("dj", "djibouti");
        this.country_codes.put("tz", "tanzania");
        this.country_codes.put("us_wv", "west virginia");
        this.country_codes.put("dk", "denmark");
        this.country_codes.put("dm", "dominica");
        this.country_codes.put("do", "dominican republic");
        this.country_codes.put("ua", "ukraine");
        this.country_codes.put("ug", "uganda");
        this.country_codes.put("ca_nb", "new brunswick");
        this.country_codes.put("dz", "algeria");
        this.country_codes.put("um", "united states minor outlying islands");
        this.country_codes.put("ec", "ecuador");
        this.country_codes.put("ca_nl", "newfoundland and labrador");
        this.country_codes.put("ee", "estonia");
        this.country_codes.put("us_fl", "florida");
        this.country_codes.put("eg", "egypt");
        this.country_codes.put("eh", "western sahara");
        this.country_codes.put("uy", "uruguay");
        this.country_codes.put("uz", "uzbekistan");
        this.country_codes.put("cn_61", "shaanxi");
        this.country_codes.put("va", "holy see (vatican city state)");
        this.country_codes.put("er", "eritrea");
        this.country_codes.put("us_wa", "washington");
        this.country_codes.put("vc", "saint vincent and the grenadines");
        this.country_codes.put("es", "spain");
        this.country_codes.put("et", "ethiopia");
        this.country_codes.put("ve", "venezuela");
        this.country_codes.put("vg", "british virgin islands");
        this.country_codes.put("vi", "u.s. virgin islands");
        this.country_codes.put("cn_64", "ningxia");
        this.country_codes.put("us_wi", "wisconsin");
        this.country_codes.put("cn_65", "xinjiang");
        this.country_codes.put("ca_mb", "manitoba");
        this.country_codes.put("cn_62", "gansu");
        this.country_codes.put("cn_63", "qinghai");
        this.country_codes.put("vn", "viet nam");
        this.country_codes.put("us_ga", "georgia");
        this.country_codes.put("vu", "vanuatu");
        this.country_codes.put("ca_on", "ontario");
        this.country_codes.put("us_in", "indiana");
        this.country_codes.put("us_il", "illinois");
        this.country_codes.put("fi", "finland");
        this.country_codes.put("fj", "fiji");
        this.country_codes.put("fk", "falkland islands (malvinas)");
        this.country_codes.put("fm", "micronesia");
        this.country_codes.put("fo", "faroe islands");
        this.country_codes.put("cn_92", "macau");
        this.country_codes.put("fr", "france");
        this.country_codes.put("wf", "wallis and futuna");
        this.country_codes.put("ca_pe", "prince edward island");
        this.country_codes.put("ga", "gabon");
        this.country_codes.put("gb", "united kingdom");
        this.country_codes.put("ws", "samoa");
        this.country_codes.put("gd", "grenada");
        this.country_codes.put("ge", "georgia");
        this.country_codes.put("gf", "french guiana");
        this.country_codes.put("gg", "guernsey");
        this.country_codes.put("gh", "ghana");
        this.country_codes.put("gi", "gibraltar");
        this.country_codes.put("us_hi", "hawaii");
        this.country_codes.put("gl", "greenland");
        this.country_codes.put("ca_ns", "nova scotia");
        this.country_codes.put("gm", "gambia");
        this.country_codes.put("ca_nt", "northwest territories");
        this.country_codes.put("gn", "guinea");
        this.country_codes.put("ca_nu", "nunavut");
        this.country_codes.put("gp", "guadeloupe");
        this.country_codes.put("gq", "equatorial guinea");
        this.country_codes.put("gr", "greece");
        this.country_codes.put("gs", "south georgia and the south sandwich islands");
        this.country_codes.put("gt", "guatemala");
        this.country_codes.put("gu", "guam");
        this.country_codes.put("gw", "guinea-bissau");
        this.country_codes.put("gy", "guyana");
        this.country_codes.put("xk", "kosovo");
        this.country_codes.put("us_id", "idaho");
        this.country_codes.put("us_ia", "iowa");
        this.country_codes.put("hk", "hong kong");
        this.country_codes.put("hm", "heard island and mcdonald islands");
        this.country_codes.put("hn", "honduras");
        this.country_codes.put("ae_du", "dubai");
        this.country_codes.put("hr", "croatia");
        this.country_codes.put("us_co", "colorado");
        this.country_codes.put("ht", "haiti");
        this.country_codes.put("ye", "yemen");
        this.country_codes.put("hu", "hungary");
        this.country_codes.put("cn_35", "fujian");
        this.country_codes.put("cn_36", "jiangxi");
        this.country_codes.put("ae_uq", "umm al-quwain");
        this.country_codes.put("cn_33", "zhejiang");
        this.country_codes.put("cn_34", "anhui");
        this.country_codes.put("us_ct", "connecticut");
        this.country_codes.put("cn_31", "shanghai");
        this.country_codes.put("cn_32", "jiangsu");
        this.country_codes.put("id", "indonesia");
        this.country_codes.put("yt", "mayotte");
        this.country_codes.put("ie", "ireland");
        this.country_codes.put("us_tn", "tennessee");
        this.country_codes.put("cn_37", "shandong");
        this.country_codes.put("il", "israel");
        this.country_codes.put("im", "isle of man");
        this.country_codes.put("in", "india");
        this.country_codes.put("io", "british indian ocean territory");
        this.country_codes.put("za", "south africa");
        this.country_codes.put("iq", "iraq");
        this.country_codes.put("ir", "iran");
        this.country_codes.put("is", "iceland");
        this.country_codes.put("it", "italy");
        this.country_codes.put("cn_22", "jilin");
        this.country_codes.put("zm", "zambia");
        this.country_codes.put("cn_23", "heilongjiang");
        this.country_codes.put("us_sd", "south dakota");
        this.country_codes.put("cn_21", "liaoning");
        this.country_codes.put("us_sc", "south carolina");
        this.country_codes.put("us_ca", "california");
        this.country_codes.put("je", "jersey");
        this.country_codes.put("ca_yt", "yukon");
        this.country_codes.put("zw", "zimbabwe");
        this.country_codes.put("jm", "jamaica");
        this.country_codes.put("jo", "jordan");
        this.country_codes.put("jp", "japan");
        this.country_codes.put("us_ut", "utah");
        this.country_codes.put("cn_50", "chongqing");
        this.country_codes.put("us_va", "virginia");
        this.country_codes.put("ae_fu", "fujairah");
        this.country_codes.put("cn_53", "yunnan");
        this.country_codes.put("cn_54", "tibet");
        this.country_codes.put("cn_51", "sichuan");
        this.country_codes.put("cn_52", "guizhou");
        this.country_codes.put("us_vt", "vermont");
        this.country_codes.put("ke", "kenya");
        this.country_codes.put("kg", "kyrgyzstan");
        this.country_codes.put("kh", "cambodia");
        this.country_codes.put("ki", "kiribati");
        this.country_codes.put("km", "comoros");
        this.country_codes.put("kn", "saint kitts and nevis");
        this.country_codes.put("us_tx", "texas");
        this.country_codes.put("us_de", "delaware");
        this.country_codes.put("kp", "democratic people's republic of korea");
        this.country_codes.put("us_dc", "district of columbia");
        this.country_codes.put("kr", "republic of korea");
        this.country_codes.put("kw", "kuwait");
        this.country_codes.put("ky", "cayman islands");
        this.country_codes.put("kz", "kazakhstan");
        this.country_codes.put("cn_46", "hainan");
        this.country_codes.put("cn_44", "guangdong");
        this.country_codes.put("cn_45", "guangxi");
        this.country_codes.put("cn_42", "hubei");
        this.country_codes.put("la", "lao people's democratic republic");
        this.country_codes.put("cn_43", "hunan");
        this.country_codes.put("lb", "lebanon");
        this.country_codes.put("lc", "saint lucia");
        this.country_codes.put("cn_41", "henan");
        this.country_codes.put("li", "liechtenstein");
        this.country_codes.put("lk", "sri lanka");
        this.country_codes.put("us_or", "oregon");
        this.country_codes.put("lr", "liberia");
        this.country_codes.put("ls", "lesotho");
        this.country_codes.put("lt", "lithuania");
        this.country_codes.put("lu", "luxembourg");
        this.country_codes.put("lv", "latvia");
        this.country_codes.put("ly", "libya");
        this.country_codes.put("ma", "morocco");
        this.country_codes.put("us_pa", "pennsylvania");
        this.country_codes.put("mc", "monaco");
        this.country_codes.put("md", "moldova");
        this.country_codes.put("me", "montenegro");
        this.country_codes.put("mf", "saint martin (french part)");
        this.country_codes.put("mg", "madagascar");
        this.country_codes.put("mh", "marshall islands");
        this.country_codes.put("mk", "macedonia");
        this.country_codes.put("ml", "mali");
        this.country_codes.put("mm", "myanmar");
        this.country_codes.put("mn", "mongolia");
        this.country_codes.put("mo", "macao");
        this.country_codes.put("ae_aj", "ajman");
        this.country_codes.put("mp", "northern mariana islands");
        this.country_codes.put("mq", "martinique");
        this.country_codes.put("mr", "mauritania");
        this.country_codes.put("ms", "montserrat");
        this.country_codes.put("us_nm", "new mexico");
        this.country_codes.put("mt", "malta");
        this.country_codes.put("mu", "mauritius");
        this.country_codes.put("mv", "maldives");
        this.country_codes.put("mw", "malawi");
        this.country_codes.put("us_ny", "new york");
        this.country_codes.put("mx", "mexico");
        this.country_codes.put("my", "malaysia");
        this.country_codes.put("mz", "mozambique");
        this.country_codes.put("us_nv", "nevada");
        this.country_codes.put("ae_az", "abu dhabi");
        this.country_codes.put("ae_rk", "ras al-khaimah");
        this.country_codes.put("na", "namibia");
        this.country_codes.put("nc", "new caledonia");
        this.country_codes.put("ne", "niger");
        this.country_codes.put("nf", "norfolk island");
        this.country_codes.put("ng", "nigeria");
        this.country_codes.put("ni", "nicaragua");
        this.country_codes.put("us_ok", "oklahoma");
        this.country_codes.put("us_oh", "ohio");
        this.country_codes.put("nl", "netherlands");
        this.country_codes.put("no", "norway");
        this.country_codes.put("np", "nepal");
        this.country_codes.put("nr", "nauru");
        this.country_codes.put("nu", "niue");
        this.country_codes.put("us_al", "alabama");
        this.country_codes.put("nz", "new zealand");
        this.country_codes.put("us_ak", "alaska");
        this.country_codes.put("cn_13", "hebei");
        this.country_codes.put("cn_14", "shanxi");
        this.country_codes.put("cn_11", "beijing");
        this.country_codes.put("cn_12", "tianjin");
        this.country_codes.put("us_ar", "arkansas");
        this.country_codes.put("ae_sh", "sharjah");
        this.country_codes.put("us_az", "arizona");
        this.country_codes.put("om", "oman");
        this.country_codes.put("us_ri", "rhode island");
        this.country_codes.put("cn_15", "inner mongolia");
        this.country_codes.put("pa", "panama");
        this.country_codes.put("pe", "peru");
        this.country_codes.put("pf", "french polynesia");
        this.country_codes.put("pg", "papua new guinea");
        this.country_codes.put("ph", "philippines");
        this.country_codes.put("pk", "pakistan");
        this.country_codes.put("pl", "poland");
        this.country_codes.put("pm", "saint pierre and miquelon");
        this.country_codes.put("pn", "pitcairn");
        this.country_codes.put("us", "united states");
        this.country_codes.put("uk", "united kingdom");
        this.country_codes.put("ae", "united arab emirates");
    }

    public String getCountry(String country_code) {
        return (String) this.country_codes.get(country_code);
    }
}
